title: "Curso de programación avanzada"
description: "Elaborado por Dr. Luis Morales Velázquez en la Universidad Autónoma de Querétaro (FI-SJR)"
theme: minima

author: Dr. Luis Morales Velázquez luis.moralesv@uaq.mx
  
header_pages:
  - index.md

markdown: kramdown

collections:
  temas:
    output: true
  fichas:
    output: true
