title: "Curso de programación avanzada"
description: "Elaborado por Dr. Luis Morales Velázquez en la Universidad Autónoma de Querétaro (FI-SJR)"
markdown: kramdown
theme: minima
collections:
  temas:
    output: true
  fichas:
    output: true
